url=https://automationexercise.com
browser=chrome
name=TestUser
password=Test@123
firstname=John
lastname=Doe
address=India
state=AP
city=Vizag
zipcode=530001
mobile=9999999999
email=pavan12@gmail.com
wrong_password=test@123
timeout=10
api_base_url=https://automationexercise.com